### ISSUE TITLE
BUG: Add Student Duplicate Allowed

### ISSUE THREAD

**Issue by bryandagamer** [SeanMcP/popsicle-sticks-extension#30]
**Associated branch**
#29 

**Describe the bug**
Adding a student with the same name as one already added didn't give any warnings, allowed duplicate name.

**To Reproduce**
 - Select class > Input repeated student name > Select "Add student" > Alert about duplicate student names

**Expected behavior**
Alert about duplicate student names

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 92.0.4515.159

**Comment by SeanMcP** [comment]
Good find! This should be fixed here in #28:

https://github.com/SeanMcP/popsicle-sticks-extension/blob/task/reduce-storage-size/src/js/class.js#L31
