### ISSUE TITLE
BUG: One name per line doesn't work

### ISSUE THREAD

**Issue by NoSubstitute** [SeanMcP/popsicle-sticks-extension#32]
**Associated branch**
#0

**Describe the bug**
Lists of names (one name per line) are added as one name

**To Reproduce**

1. Try to add Multiple Students
2. Change to _One name per line_
3. Paste names
4. Click _Add All_
5. All names are added as one name.

**Expected behavior**
Names should be added as separate names.
**Screenshots**
![Skärmavbild 2022-08-18 kl  13 03 25](https://user-images.githubusercontent.com/12572734/185380227-90e28bf8-484f-4db8-bc11-3ede152783dc.png)

![Skärmavbild 2022-08-18 kl  13 03 53](https://user-images.githubusercontent.com/12572734/185380224-b76975c2-6587-48e3-93c2-b4ab2111c3bc.png)

![Skärmavbild 2022-08-18 kl  13 04 05](https://user-images.githubusercontent.com/12572734/185380215-54f70fb9-dcde-41fc-8d07-8ee7c3520273.png)

**Desktop (please complete the following information):**
 - OS: macOS Montery
 - Browser Chrome 104.0.5112.101
 - Version 1.4.1

**Additional context**
Adding names separated by comma works.

**Comment by SeanMcP** [comment]
Uh oh! I am able to reproduce this, so I will take a look at a fix.

**Comment by SeanMcP** [comment]
@NoSubstitute The fix has been submitted to the Chrome Web Store and will be available to you shortly! Thanks for contributing here in GitHub 👍
