### ISSUE TITLE
FEATURE: Upgrade to Manifest V3

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/popsicle-sticks-extension#36]
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

**Comment by NoSubstitute** [comment]
Hi, how hard do you think the is going to be?
I fear I may have to do that with my own addon, as it was created before mv3 was relevant.
As a one-man-show I'd love to do as little work, as few changes as possible, which I assume you are aiming for too.

**Comment by SeanMcP** [comment]
Hey! I'm anticipated the changes for my extension to be pretty straightforward:
- `background.scripts` ➡️ `background.service_worker`
- `browser_action` ➡️ `action`

That said, I haven't tried doing it yet so we will see!
